### ISSUE TITLE
使用库时的一些疑问

### ISSUE THREAD

**Issue by 1longlong1** [lovemengx/libinimini#1]
#include "common/framework/fs_ctrl.h"
#include "common/framework/platform_init.h"
这两个头文件没有，应该从哪里下载呢？

在FREERTOS的案例中，因为没有对应的头文件，这几行编译无法通过，也无法成功打开ini文件，希望作者可以补充一下
	platform_init();
	if(fs_ctrl_mount(FS_MNT_DEV_TYPE_SDCARD, 0) != FS_MNT_STATUS_MOUNT_OK){
		printf("fs mount failed\n");
		while(1) OS_Sleep(1);
	}

**Comment by lovemengx** [comment]
这两个头文件是 xr872 sdk 内置的，只是一个可以在 MCU 跑的示例代码，本身这个库是不需要这两个头文件的。
